name: publishBackend.yaml

on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs: 
  build_docker_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
    - uses: actions/checkout@v2 

    - name: Install dependencies、build and generate jar
      run: ./mvnw clean package

    - name: build docker image
      run: |
          docker build . --file Dockerfile --tag ccr.ccs.tencentyun.com/jiladahe1997/embeddproxy:latest
          docker login -u 972931182 -p ${{secrets.dockerPassword}} ccr.ccs.tencentyun.com
          docker push ccr.ccs.tencentyun.com/jiladahe1997/embeddproxy:latest

  redeploy_Tencent_TKE_cluster_service:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2 

    - name: RedeployClusterService
      run: node publishServer ${{secrets.SecretId}} ${{secrets.SecretKey}}
 
  